export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const CART_CLEAR = "CART_CLEAR";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const PAY_REQUEST = "PAY_REQUEST";
export const PAY_SUCCESS = "PAY_SUCCESS";
export const PAY_FAIL = "PAY_FAIL";
export const PAY_RESET = "PAY_RESET";
export const DELIVER_RESET = "DELIVER_RESET";
export const DELIVER_SUCCESS = "DELIVER_RSUCCESS";
export const DELIVER_FAIL = "DELIVER_FAIL";
export const DELIVER_REQUEST = "DELIVER_REQUEST";
export const FETCH_REQUEST_PRODUCTS = "FETCH_REQUEST_PRODUCTS";
export const FETCH_SUCCESS_PRODUCTS = "FETCH_SUCCESS_PRODUCTS";
export const FETCH_FAIL_PRODUCTS = "FETCH_FAIL_PRODUCTS";

export const FETCH_REQUEST_PRODUCT = "FETCH_REQUEST_PRODUCT";
export const FETCH_SUCCESS_PRODUCT = "FETCH_SUCCESS_PRODUCT";
export const FETCH_FAIL_PRODUCT = "FETCH_FAIL_PRODUCT";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const UPLOAD_REQUEST = "UPLOAD_REQUEST";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";

export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAIL = "DELETE_FAIL";
export const DELETE_RESET = "DELETE_RESET";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const SET_DARK_MODE = "SET_DARK_MODE";
